### ISSUE TITLE
Add an optional maxPerAddress parameter in the marketplace

### ISSUE THREAD

**Issue by damienen** [Itheum/itheumcore-elrond-data-nft-marketplace#45]
Requirements:
1. Whenever someone lists they can specify an optional maxQuantity parameter which limits how many of those NFTs an address can buy
2. If they don't send such a parameter, the maxDefaultQuantity is set to be used instead

**Comment by bucurdavid** [comment]
Should be delivered with this PR: https://github.com/Itheum/sdk-mx-data-nft/pull/129

**Comment by damienen** [comment]
Seems like you added a maxQuantity per TX, but a max quantity per ADDRESS is needed. (see updated descriprition above as well)

**Comment by damienen** [comment]
Code reviewed. Looks good. But to be noted: it's a breaking changes for the addOffer endpoint

**Comment by damienen** [comment]
https://github.com/Itheum/itheumcore-elrond-data-nft-marketplace/blob/ce15a874eb1661145d71ab19313eef0850e17d9e/src/storage.rs#L29

We should return how much the user can buy on his address for each offer in offer out (not how much IN TOTAL, but how much considering what he has bought so far)

**Comment by damienen** [comment]
Solved. Closing
